# Stage 1: Builder
FROM node:17-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . ./

RUN chown -R node:node /app && \
	npm run build 2>&1 | tee /app/build.log || (cat /app/build.log && exit 1)

# Stage 2: Production
FROM nginx:1.23-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/build.log /var/log/ 