services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: college_schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - college_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 10s

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - college_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_grace_period: 10s

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - college_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    stop_grace_period: 15s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/college_schedule
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - college_network
    stop_grace_period: 10s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - college_network
    stop_grace_period: 10s

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: celery -A backend worker -l INFO
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/college_schedule
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - college_network
    stop_grace_period: 10s

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./api.yaml
    environment:
      SWAGGER_JSON: ./api.yaml

volumes:
  postgres_data:

networks:
  college_network:
    driver: bridge